on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.2.0
        with:
          token: ${{ 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 }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.example.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
